run_name: "simple_net"

dataset: "CIFAR10"
batch_size: 64
num_workers: 0

label_corruption_prob: 0.
data_corruption_type: "none"
data_corruption_prob: 0.

model_name: "Net"

learning_rate: 0.01
momentum: 0.9
weight_decay: 0.
num_epochs: 60
lr_decay: 0.95

log_every: 20  # compute metrics after ... batches
batch_window: 50  # use the previous ... batches to compute the metrics
checkpoint_dir: "checkpoints/Net"
checkpoint_every: 50  # save the model every ... epochs