dataset: "CIFAR10"
test_size: 0.2  # train-test split
batch_size: 64
num_workers: 0  # 0 when no augmentations are used

label_corruption_prob: 0.  # start with original labels
data_corruption_type: "none"  # start with original data

model_name: "Net"

learning_rate: 0.01
momentum: 0.9
weight_decay: 0.
num_epochs: 10
lr_decay: 0.95

log_every: 20  # compute metrics after ... batches
batch_window: 50  # use the previous ... batches to compute the metrics

checkpoint_dir: "checkpoints/Net"
checkpoint_every: 10  # save the model every ... epochs
resume_checkpoint: "checkpoints/Net/e_002_Net_simple_net.pt"

comet_project: "deep-learning-generalization"
experiment_name: "simple_net"
experiment_key: "f83e26a862f148aeb7d167dc4aba897b"